[package]
name = "rust_os"
version = "0.1.0"
authors = ["Johann Barnard <johann.b@telus.net>"]
edition = "2018"

[dependencies]
bootloader = "0.6.0"
volatile = "0.2.6"
spin = "0.5.0"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
